version: '3.4'

services:
  informeaquiapi:
    image: informeaquiapi:dev
    container_name: "InformeAquiAPI"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "InformeAquiAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\renzo.takada\Documents\projetosPoc\InformeAquiAPI\InformeAquiAPI:/app:rw
      - C:\Users\renzo.takada\Documents\projetosPoc\InformeAquiAPI:/src:rw
      - C:\Users\renzo.takada\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\renzo.takada\.nuget\packages:/.nuget/packages:ro
      - C:\Users\renzo.takada\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\renzo.takada\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\renzo.takada\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\renzo.takada\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net6.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net6.0/InformeAquiAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true